#!/bin/bash
port=$(echo -n "$1" | sed 's,.*local.*:\([^/]*\)/.*,\1,')
token=$(echo -n "$1" | sed 's,.*token=,,')
export AFM_APP_INSTALL_DIR=$(mktemp -d)
cat << EOC >  $AFM_APP_INSTALL_DIR/runxdg.toml
[application]
role = "WebBrowser-$port" 
method = "POSIX" 
path = "/usr/bin/chromium" 
params = [
     "--app=$1",
     "--kiosk",
     "--disable-infobars",
     "--window-size=1050,1446",
     "--no-sandbox",
     "--incognito",
     "--user-data-dir=$AFM_APP_INSTALL_DIR",
]
EOC
/usr/bin/runxdg "$port" "$token" 
rm -rf $AFM_APP_INSTALL_DIR

#     "--autoplay-policy=no-user-gesture-required",
#     "--window-size=720,992",
#     "--incognito",

